FROM node:22-alpine

WORKDIR /app


# Copiar o restante projeto
COPY package.json .
COPY package-lock.json .

RUN npm ci

RUN npm install -g http-server

COPY . .

# Build Vite
RUN npm run build


# Create group and user before changing ownership
RUN addgroup -S appgroup && adduser -S user -G appgroup

# Change ownership of the /app folder
RUN chown -R user:appgroup /app

# Switch to the new user
USER user

# Expor porta
EXPOSE 5173

# Servir a pasta dist
CMD ["http-server", "dist", "-p", "5173"]