# Imagem base Python (leve)
FROM python:3.12-slim

# Diretório de trabalho
WORKDIR /app

# Copiar dependências (se existirem)
COPY requirements.txt* ./

# Instalar dependências (ignora se o ficheiro não existir)
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi


RUN mkdir gdb

# Copiar o resto do código para dentro do container
COPY . ./gdb/

# Create group and user before changing ownership
RUN groupadd -r appgroup && useradd -r -g appgroup user

# Change ownership of the /app folder
RUN chown -R user:appgroup /app

# Switch to the new user
USER user

# Expor a porta do backend
EXPOSE 5050

# Comando genérico (substituir mais tarde pelo da tua app real)
CMD ["python", "-m", "gdb.app", "5050"]