# Imagem base Python (leve)
FROM python:3.12-slim


RUN apt-get update && apt-get install -y \
    libexpat1 \
    libgdal-dev \
    gdal-bin \
    libproj-dev \
    libgeos-dev \
    && rm -rf /var/lib/apt/lists/*

# Diretório de trabalho
WORKDIR /app

# Copiar dependências (se existirem)
COPY requirements.txt* ./

# Instalar dependências (ignora se o ficheiro não existir)
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi


RUN mkdir App

# Copiar o resto do código para dentro do container
COPY . ./App/

# Create group and user before changing ownership
#RUN groupadd -r appgroup && useradd -r -g appgroup user

# Change ownership of the /app folder
#RUN chown -R user:appgroup /app

# Switch to the new user
#USER user

# Expor a porta do backend
EXPOSE 5050

# Comando genérico (substituir mais tarde pelo da tua app real)
CMD ["python", "-m", "App.app", "5050"]